### ISSUE TITLE
Need to delete tagged message

### ISSUE THREAD

**Issue by ogorodnikovInfopulse** [backmeupplz/banofbot#11]
After deleting user from chat after votin - spam message exists. It will be fine if you add possibility to delete tagged message with kicking user from chat. Delete only shown messages, not all from this user (if kicked real user - do not need to delete all his messages, only spam)
![image](https://user-images.githubusercontent.com/48473587/54810008-92e39980-4c8d-11e9-8f50-7aabe262ad46.png)

**Comment by backmeupplz** [comment]
Weird, it already works like this. Please, make sure that banofbot has delete messages permission.

**Comment by backmeupplz** [comment]
@ogorodnikovInfopulse confirmed, it works as you suggested. Also, t.me/shieldy_bot with the digits captcha may work better for your case :)

<img width="566" alt="Screen Shot 2019-03-25 at 5 19 33 PM" src="https://user-images.githubusercontent.com/3192028/54962473-3e0c8100-4f22-11e9-8e41-e57755223cb2.png">
