### ISSUE TITLE
Self ban

### ISSUE THREAD

**Issue by glader** [backmeupplz/banofbot#12]
Я заметил, что при появлении голосования за то, чтобы забанить бота, многие боты тоже голосуют за. Возможно, это особенность их алгоритма. Предлагаю использовать её на благо. Если пользователь голосует за то, чтобы забанить его же, то банить сразу, не дожидаясь кворума.

**Comment by backmeupplz** [comment]
Иногда люди так шуткуют — пытаясь вызвать на себя голосование. Для самозабана есть /banme :) но спасибо за предложение

**Comment by glader** [comment]
Похоже, я недостаточно понятно изложил. Не претендуя на продолжение дискуссии, разверну свою мысль.

Рекламный бот приходит в чат. Публикует рекламу. Пользователи призывают банбота. Включается голосование. Если кворум набирается, рекламный бот уходит в бан. Кворума приходится ждать некоторое время. Можно ускорить этот процесс, если отслеживать, проголосовал ли за бан тот бот, на которого жалуются. По моей логике, если человек не хочет быть в чате, он из него выйдет. Значит за себя голосую только тупой бот. И это доп признак, что его можно забанить, не дожидаясь кворума.

![2019-04-09_16-07-46](https://user-images.githubusercontent.com/494361/55802884-cde52a00-5ae1-11e9-854a-88df4299b609.png)
