### ISSUE TITLE
Reputation system

### ISSUE THREAD

**Issue by Lonami** [backmeupplz/banofbot#14]
[To avoid things like this](https://t.me/telethonofftopic/254581):
> One genius added a banofbot to his chat and after some 5 random guys with userbots joined all 500 participants were banned by him in 1 minute.

[You could do something like this](https://t.me/telethonofftopic/254585):
> Should've had a blacklist + whitelist or reputation system
> […]
> and maybe ignore votes if user isn't chat participant

**Comment by backmeupplz** [comment]
Either use https://t.me/shieldy_bot or set up `/time` in banofbot :)
