### ISSUE TITLE
Access to commands for bare users.

### ISSUE THREAD

**Issue by SeYearSt** [backmeupplz/banofbot#19]
If I'm user a non-admin user and I can use command so I can use /lock and lock myself that is unpleasant. And it is not only about regular user. Spamer can performe same actions and  delay blocking until admin comes.

**Comment by backmeupplz** [comment]
It's not a bug, this behavior is expected.

**Comment by justOleh** [comment]
How useful it is?

**Comment by backmeupplz** [comment]
When a non-admin adds a bot they can set it up and lock before admins come back and give the bot kicking rights.
