### ISSUE TITLE
bot.restrictChatMember

### ISSUE THREAD

**Issue by azharkov78** [backmeupplz/banofbot#28]
Добрый день
Хочу заменить bot.kickChatMember(request.chat.id, request.candidate.id) на bot.restrictChatMember для ограничения отправки сообщений на определённое время
Все хорошо отрабатывает, но если пользователь был ограничен (кикнут), он снова не может голосовать, пока не выйдет и зайдет снова в группу. Уже и базу новую создавал, ситуация не меняется

**Comment by azharkov78** [comment]
Ошибся разделом

**Comment by backmeupplz** [comment]
Не уверен, что могу помочь в этом вопросе. Подобные модификации не поддерживаются оригинальным кодом.
