### ISSUE TITLE
User's with out usernames

### ISSUE THREAD

**Issue by WaffleWafflerov** [backmeupplz/banofbot#3]
If user with out username press the kick or save button, when poll ends banofbot will display just it name.

But telegram bot api provides Markdown/HTML formatting, so it is possible to display "links" on users. 

With HTML link to user will be something like that: `"<a href='tg://user?id=USER_ID'>NAME</a>"`

**Comment by backmeupplz** [comment]
Hm, good idea as well, worth implementing, thanks!

**Comment by backmeupplz** [comment]
Done :)
