### ISSUE TITLE
Watching in embedded links

### ISSUE THREAD

**Issue by WaffleWafflerov** [backmeupplz/banofbot#4]
I just write message in telegram with link to your github replying my old message and bot starts poll for kicking me! So i think bot wathing in links preview.
Screenshoot:
https://drive.google.com/file/d/0B7QA3RAqIPLYSXRaNmNpVUQ2T0lteWJILTZUaFc0aHE1dUhJ/view?usp=sharing

**Comment by backmeupplz** [comment]
Nah, it's actually not a bug. It reacts to any replies with `banofbot` in it :)
