### ISSUE TITLE
Remove all chat messages when kicking user

### ISSUE THREAD

**Issue by Arunmor1510** [backmeupplz/banofbot#44]
Hi, I find that banofbot is a very good bot, however it seems that when kicking a user, the user is banned and only one message is deleted, I hope there can be a option to delete all chat history of this user.

banofbot uses api kickChatMember, which is renamed to [banChatMember](https://core.telegram.org/bots/api#banchatmember), according to [api changelog](https://core.telegram.org/bots/api-changelog#november-5-2021) , the old one is still useable, and it has a option "revoke_messages" to delete all messages from the chat for the user that is being removed . I don't know about node bot api, but maybe we can try to add this option? Theoretically it should work. It will be very helpful, thanks.

**Comment by backmeupplz** [comment]
Hm, this sounds helpful

**Comment by backmeupplz** [comment]
Not sure if I have the capacity to pick this task up though :( but happy to review and merge PRs!

**Comment by TrashAccount3424** [comment]
> Hi, I find that banofbot is a very good bot, however it seems that when kicking a user, the user is banned and only one message is deleted, I hope there can be a option to delete all chat history of this user.
> 
> banofbot uses api kickChatMember, which is renamed to [banChatMember](https://core.telegram.org/bots/api#banchatmember), according to [api changelog](https://core.telegram.org/bots/api-changelog#november-5-2021) , the old one is still useable, and it has a option "revoke_messages" to delete all messages from the chat for the user that is being removed . I don't know about node bot api, but maybe we can try to add this option? Theoretically it should work. It will be very helpful, thanks.

revoke_messages does NOT delete the messages in the chat for the rest of the users, it deleted them for the user that is being banned. 
The difference between setting it to true and false is that in once case the chat will stay for the banned user and he can see everything up to the point he was banned. If its set to true the chat will disappear.
This is only for legacy groups so in almost all cases this parameter is ignored anyway.
