### ISSUE TITLE
Start voting on ban if user calls `/help@banofbot`

### ISSUE THREAD

**Issue by Mart-Bogdan** [backmeupplz/banofbot#5]
![image](https://user-images.githubusercontent.com/775038/42775982-734756b0-893e-11e8-8b63-66e7cc296448.png)

Some uysers start spaming chat with call to `/help` action

I don't know why they click it 3 times, but that's common case. WOuld be nice to ban if someone is stupid enaught to tap "telegram autcomplete" nore than once.

**Comment by backmeupplz** [comment]
hey, unfortunately, it's a Telegram "feature" :( I believe it can be fixed if banofbot would delete the messages like this... worth thinking, thanks!

**Comment by Mart-Bogdan** [comment]
Hm, yes, deleting it would be helpful too, good idea :-)

**Comment by Mart-Bogdan** [comment]
@backmeupplz strange, is it deployed? tested sendnng /help command, and nothing happened

**Comment by backmeupplz** [comment]
@Mart-Bogdan it is :) but looks like something broke it, reopening.
