### ISSUE TITLE
limit frequency of ban activations within a time period

### ISSUE THREAD

**Issue by shelleybridge** [backmeupplz/banofbot#6]
With the proliferation of cloned accounts in telegram, the instance of malicious attack by a single or group of people using cloned accounts to outvote and mass ban members indiscriminately during non-peak graveyard hours is an increasing risk. By having a parameter to set total number of allowable bans within a time period (e.g. 10 bans within a 24-hour time frame) will prevent such mass ban flooding as a result of this malicious intent.

**Comment by shelleybridge** [comment]
if the above suggestion is not easy to implement, perhaps just having a minimum time period from last ban user set parameter will suffice (e.g. last ban must have been x mins before new ban voting can happen). the time lag between each new ban may be enough to dissuade such ban flooding attacks

**Comment by shelleybridge** [comment]
Cool! Thanks so much for your time and effort in doing this. cheers mate

**Comment by backmeupplz** [comment]
@shelleybridge you can now specify the time limit in /time ;)
