### ISSUE TITLE
Banofbot deletes messages

### ISSUE THREAD

**Issue by Adem1987** [backmeupplz/banofbot#7]
The bot deleted this message:

LC-RV 105 
ist das ein Uber-/RocVin-Fahrzeug?
Wird gerade in der Dirksen/Ecke Karl-Liebknecht-Str vom Abschleppdienst aufgeladen, nachdem die Polizei in Manschaftswagenstärke über eine Stunde um den Fahrer und das Fahrzeug herumstanden.

Time: 15.08. at 3:53.

**Comment by shelleybridge** [comment]
seems like banofbob has started indiscriminately 

deleting command based messages today - e.g. those interacting with other bots like"/c" and "/p" commands for some reason. 

![bob](https://user-images.githubusercontent.com/35885931/44137413-f37dc898-a0a2-11e8-8ebf-5abfced1eda3.png)

**Comment by backmeupplz** [comment]
Hmm, I'll investigate. Thanks for the report

**Comment by backmeupplz** [comment]
should be fixed now
