### ISSUE TITLE
vote registered for same user multiple times

### ISSUE THREAD

**Issue by shelleybridge** [backmeupplz/banofbot#9]
A user reported clicking vote button 4x and it all registered. votes should be limited to 1 per user?  User = @z_236 in this instance: https://t.me/CryptoSG/733853

**Comment by backmeupplz** [comment]
Happens sometimes due to the asynchronous nature of the telegram callbacks. Will investigate how to fix it. Thanks for the report!

**Comment by darvesh** [comment]
This happened here 
https://github.com/backmeupplz/banofbot/issues/9
